### ISSUE TITLE
CSS Modules aren't tree shaked

### ISSUE THREAD

**Issue by StarpTech** [developit/microbundle#632]
I'd expect that unused CSS is removed from the build. This is one big advantage of CSS Modules.

Example:

### Input
```jsx
import styles from './index.module.css';

export default function Button() {
    return <div className={styles.button}></div>
}
```

```css
.button {
  width: auto;
}
.unused {
  width: auto;
  padding: 3px;
}
```

### Output
```css
._2wMHH,._3X3pB{width:auto}._2wMHH{padding:3px}
```
