### ISSUE TITLE
All CSS-files are treated as CSS Modules

### ISSUE THREAD

**Issue by artemtam** [developit/microbundle#653]
Regardless `--css-modules` flag, it is impossible to use CSS and CSS Modules in the same project. It seems that `null` option works incorrectly and Rollup treats all CSS files as modules.

To reproduce, you could try to build this simple example:

```jsx
import React from 'react';

import './index.css'
import styles from './index.module.css';

const App = () => (
  <div>
    <div className={styles.moduleClass}>CSS module class</div>
    <div className="local-no-module-class">No-module class</div>
  </div>
);

export default App;
```

Building with `microbundle ./index.jsx` makes the following `index.css` file:
```css
._1fWqO{color:#00f}
._3umtn{color:red}
```

However, the expected result is: 

```css
._1fWqO{color:#00f}
.local-no-module-class{color:red}
```
